"""REPORT.md results section: auto-filled from results/*.csv, in place.

Only the region between the markers below is regenerated; the hand-written
implementation log in REPORT.md is preserved untouched.

<!-- RESULTS:BEGIN -->
... generated ...
<!-- RESULTS:END -->
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

BEGIN = "<!-- RESULTS:BEGIN -->"
END = "<!-- RESULTS:END -->"


def _to_md(df: pd.DataFrame) -> str:
    """Minimal markdown-table formatter (no tabulate dependency)."""
    cols = list(df.columns)
    def cell(v) -> str:
        if isinstance(v, float):
            return "--" if v != v else f"{v:.4f}".rstrip("0").rstrip(".")
        return str(v)

    lines = [
        "| " + " | ".join(str(c) for c in cols) + " |",
        "| " + " | ".join("---" for _ in cols) + " |",
    ]
    for _, row in df.iterrows():
        lines.append("| " + " | ".join(cell(row[c]) for c in cols) + " |")
    return "\n".join(lines)


def _load(results_dir: Path, name: str) -> Optional[pd.DataFrame]:
    path = results_dir / name
    if not path.exists():
        return None
    df = pd.read_csv(path)
    return df if not df.empty else None


def render_results_section(results_dir: Path) -> str:
    """Render the results block from whatever CSVs exist (never fabricates)."""
    parts = [
        BEGIN,
        "_Generated by `python -m armada.run --config configs/main.yaml --stage figures`. "
        "This section is overwritten on every figures run; everything outside the "
        "markers is hand-maintained._",
        "",
    ]

    overall = _load(results_dir, "metrics_all.csv")
    if overall is not None:
        parts.append("## Overall results (mean ± std over seeds)")
        parts.append("")
        cols = [c for c in overall.columns if c.endswith("_mean") or c in ("method", "n_seeds")]
        parts.append(_to_md(overall[cols].round(4)))
        parts.append("")
    else:
        parts.append("_Overall results pending (metrics_all.csv not found)._")
        parts.append("")

    rob = _load(results_dir, "robustness.csv")
    if rob is not None and ("auc_roc" in rob.columns or "accuracy" in rob.columns):
        value = "auc_roc" if "auc_roc" in rob.columns else "accuracy"
        pivot = rob.pivot_table(index="method", columns=["attack", "epsilon"], values=value, aggfunc="mean")
        parts.append("## Robustness (feature-space attacks)")
        parts.append("")
        parts.append(_to_md(pivot.round(4).reset_index()))
        parts.append("")

    dec = _load(results_dir, "decision_report.csv")
    if dec is not None:
        parts.append("## Decision engine routing")
        parts.append("")
        cols = [c for c in ("method", "window", "n_safe", "n_suspicious", "n_malware",
                            "sandbox_rate", "malware_threshold", "suspicious_threshold")
                if c in dec.columns]
        parts.append(_to_md(dec[cols].round(4)))
        parts.append("")

    sig = _load(results_dir, "significance.csv")
    if sig is not None:
        parts.append("## Paired significance (exact sign-flip, per seed)")
        parts.append("")
        parts.append(_to_md(sig.round(4)))
        parts.append("")

    abl = _load(results_dir, "ablation.csv")
    if abl is not None and "ablation" in abl.columns:
        parts.append("## Ablations")
        parts.append("")
        if "auc_roc" in abl.columns:
            g = abl.groupby("ablation")[["auc_roc"]].mean().round(4).reset_index()
            parts.append(_to_md(g))
            parts.append("")

    scale = _load(results_dir, "scale_study.csv")
    if scale is not None and "scale_point" in scale.columns:
        parts.append("## Scale study")
        parts.append("")
        if "auc_roc" in scale.columns:
            g = scale.groupby("scale_point")[["auc_roc"]].mean().round(4).reset_index()
            parts.append(_to_md(g))
            parts.append("")

    parts.append(END)
    return "\n".join(parts)


def update_report(report_path: Path, results_dir: Path) -> Path:
    """Regenerate the marker-delimited results section of REPORT.md."""
    section = render_results_section(results_dir)
    if report_path.exists():
        text = report_path.read_text()
        if BEGIN in text and END in text:
            head = text.split(BEGIN)[0]
            tail = text.split(END, 1)[1]
            text = head + section + tail
        else:
            text = text.rstrip() + "\n\n" + section + "\n"
    else:
        text = f"# ARMADA — implementation & results report\n\n{section}\n"
    report_path.write_text(text)
    logger.info("updated results section of %s", report_path)
    return report_path
